language: php
sudo: false

branches:
  only:
    - master
    - staging
    - travis

cache:
  directories:
    - ~/.composer/cache/files
    - vendor

php:
  - 5.5
  - 5.6

env:
  global:
    - DB=mysql
  matrix:
    - MAGENTO_VERSION="magento-mirror-1.4.2.0" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.5.1.0" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.6.2.0" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.7.0.2" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.8.1.0" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.1" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.2.4" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.0" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.1" INSTALL_SAMPLE_DATA=no
    - MAGENTO_VERSION="magento-mirror-1.9.3.2" INSTALL_SAMPLE_DATA=no

matrix:
  fast_finish: true
  exclude:
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.8.1.0" DB=mysql INSTALL_SAMPLE_DATA=no
  include:
    - php: 7.0
      env: LINTSH=1
      script: find {src,tests} -name "*.php" ! -path '*/String.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.2.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.2.4" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.0" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.1" DB=mysql INSTALL_SAMPLE_DATA=no
    - php: 7.0
      env: MAGENTO_VERSION="magento-mirror-1.9.3.2" DB=mysql INSTALL_SAMPLE_DATA=no

before_install:
#  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
#  - travis_retry composer global require hirak/prestissimo

install:
  - travis_retry composer install --prefer-source --no-interaction --ignore-platform-reqs
  - composer dump-autoload --optimize

before_script:
  - source build/travis/before_script.sh

script:
  - vendor/bin/phpspec run -f pretty -v
  - vendor/bin/phpunit --coverage-clover=coverage.xml -v --debug

after_success:
  - bash <(curl -s https://codecov.io/bash) -t ab97c4b0-1089-43fd-839e-203740338352